// Category-specific configuration for provider onboarding
// Each category drives tailored fields, tips, service templates, and pricing guidance

export const PROVIDER_CATEGORIES = [
  {
    id: "beauty_wellness",
    label: "Beauty & Wellness",
    emoji: "💅",
    color: "from-pink-600 to-rose-600",
    subcategories: ["Hair Stylist", "Nail Technician", "Makeup Artist", "Massage Therapist", "Esthetician", "Barber"],
    serviceTemplates: [
      { title: "Full Hair & Style Session", price: 120, duration: 90, price_type: "fixed" },
      { title: "Eyebrow Threading / Waxing", price: 35, duration: 30, price_type: "fixed" },
      { title: "Relaxation Massage (60 min)", price: 80, duration: 60, price_type: "fixed" },
    ],
    tips: [
      "Upload a portfolio of your best work — photos convert clients",
      "Enable instant booking to capture impulse bookings",
      "Offer bundle packages to increase average order value",
    ],
    businessHint: "Do you offer mobile/in-home services? Enable your service area to attract more clients.",
    availabilityNote: "Beauty services are most booked on Fri–Sun. Consider extended evening hours.",
    pricingNote: "South Florida beauty services average $60–$200/hr. Position competitively.",
    marketplaceCategory: "barber_beauty",
  },
  {
    id: "photography_video",
    label: "Photography & Video",
    emoji: "📸",
    color: "from-blue-600 to-cyan-600",
    subcategories: ["Portrait Photography", "Event Photography", "Wedding", "Commercial", "Real Estate", "Videography"],
    serviceTemplates: [
      { title: "Portrait Session (1 hr)", price: 250, duration: 60, price_type: "fixed" },
      { title: "Event Coverage (4 hrs)", price: 800, duration: 240, price_type: "fixed" },
      { title: "Real Estate Photography", price: 350, duration: 120, price_type: "per_project" },
    ],
    tips: [
      "Showcase a curated gallery — your best 12 images are your storefront",
      "Add turnaround time to your description to set expectations",
      "Offer rush delivery as a paid add-on",
    ],
    businessHint: "Add your shooting locations and travel radius to get found by local clients.",
    availabilityNote: "Weekend bookings dominate photography. Block personal time proactively.",
    pricingNote: "Package pricing outperforms hourly for photo/video — clients prefer predictability.",
    marketplaceCategory: "photography",
  },
  {
    id: "food_catering",
    label: "Food & Catering",
    emoji: "🍽️",
    color: "from-orange-600 to-amber-600",
    subcategories: ["Personal Chef", "Meal Prep", "Event Catering", "Private Dining", "Baked Goods", "Food Truck"],
    serviceTemplates: [
      { title: "Weekly Meal Prep (5 meals)", price: 200, duration: 180, price_type: "fixed" },
      { title: "Private Dinner (2–4 guests)", price: 350, duration: 240, price_type: "per_project" },
      { title: "Event Catering (per person)", price: 45, duration: 360, price_type: "per_project" },
    ],
    tips: [
      "List dietary specializations (vegan, gluten-free, halal) to attract niche clients",
      "Require 48-hour advance booking for catering events",
      "Add a menu PDF link in your description for event clients",
    ],
    businessHint: "Upload photos of signature dishes — food photos are the #1 booking driver.",
    availabilityNote: "Require minimum notice (2–3 days) for catering to manage prep time.",
    pricingNote: "Minimum order requirements protect your time. Set a minimum booking value.",
    marketplaceCategory: "catering",
  },
  {
    id: "fitness_training",
    label: "Fitness & Training",
    emoji: "💪",
    color: "from-green-600 to-emerald-600",
    subcategories: ["Personal Trainer", "Yoga Instructor", "Pilates", "Boxing Coach", "Nutritionist", "Sports Coach"],
    serviceTemplates: [
      { title: "1-on-1 Personal Training Session", price: 75, duration: 60, price_type: "hourly" },
      { title: "Monthly Training Package (12 sessions)", price: 720, duration: 60, price_type: "per_month" },
      { title: "Online Coaching (Monthly)", price: 199, duration: 0, price_type: "per_month" },
    ],
    tips: [
      "Offer a free intro session — it converts browsers to long-term clients",
      "Monthly packages reduce churn and provide predictable income",
      "Add your certifications (NASM, ACE, etc.) for trust signals",
    ],
    businessHint: "Can you travel to clients? In-home training commands a 20–30% premium.",
    availabilityNote: "Early morning (6–9am) and evening (5–8pm) slots fill fastest for fitness.",
    pricingNote: "Package pricing (10- or 20-session bundles) increases revenue 2–3x vs single sessions.",
    marketplaceCategory: "fitness_training",
  },
  {
    id: "home_services",
    label: "Home Services",
    emoji: "🔧",
    color: "from-slate-600 to-blue-700",
    subcategories: ["Plumber", "Electrician", "HVAC", "Cleaner", "Landscaper", "Painter", "Handyman", "Interior Design"],
    serviceTemplates: [
      { title: "Home Deep Clean (1–2 bed)", price: 180, duration: 180, price_type: "fixed" },
      { title: "Lawn Mowing & Edging", price: 65, duration: 60, price_type: "per_project" },
      { title: "Hourly Handyman Service", price: 85, duration: 60, price_type: "hourly" },
    ],
    tips: [
      "List your service area clearly — homeowners search by zip code",
      "Response time is critical — reply within 1 hour to win bookings",
      "Add before/after photos to build trust",
    ],
    businessHint: "Upload your license and insurance certificate to unlock the Verified badge.",
    availabilityNote: "Weekday daytime slots are preferred by homeowners for access to their property.",
    pricingNote: "Offer a free estimate call or site visit to win larger jobs.",
    marketplaceCategory: "home_services",
  },
  {
    id: "events_entertainment",
    label: "Events & Entertainment",
    emoji: "🎉",
    color: "from-purple-600 to-violet-600",
    subcategories: ["Event Planner", "DJ", "Live Band", "Photo Booth", "Decor", "Comedian", "Magician", "MC/Host"],
    serviceTemplates: [
      { title: "DJ Set (4 hrs)", price: 600, duration: 240, price_type: "fixed" },
      { title: "Event Planning Consultation", price: 150, duration: 60, price_type: "hourly" },
      { title: "Full Event Decor Package", price: 1200, duration: 480, price_type: "per_project" },
    ],
    tips: [
      "Add a demo video or music mix link in your description",
      "Show photos from real events you've worked",
      "List your equipment setup for DJ/band/AV clients",
    ],
    businessHint: "Peak season is Oct–Apr in South Florida. Block your calendar early.",
    availabilityNote: "Require a deposit (30–50%) at booking for events to protect your time.",
    pricingNote: "Minimum booking fees protect against small gigs that aren't worth your setup time.",
    marketplaceCategory: "dj_entertainment",
  },
  {
    id: "professional_services",
    label: "Professional Services",
    emoji: "💼",
    color: "from-indigo-600 to-blue-600",
    subcategories: ["Consultant", "Accountant", "Tax Preparer", "Attorney", "Marketing", "HR", "Business Coach", "VA"],
    serviceTemplates: [
      { title: "Business Strategy Consultation (1 hr)", price: 200, duration: 60, price_type: "hourly" },
      { title: "Monthly Marketing Retainer", price: 1500, duration: 0, price_type: "per_month" },
      { title: "Tax Preparation (Individual)", price: 350, duration: 120, price_type: "per_project" },
    ],
    tips: [
      "Add LinkedIn and credentials to your profile for B2B trust",
      "Case studies and results outperform generic descriptions",
      "Offer a free 30-min discovery call as a lead magnet",
    ],
    businessHint: "Enable contract/escrow-backed payments for high-value retainer clients.",
    availabilityNote: "Business hours Mon–Fri are standard; weekend availability can be a differentiator.",
    pricingNote: "Retainer pricing creates recurring revenue — promote monthly packages.",
    marketplaceCategory: "consulting",
  },
  {
    id: "vehicle_rental",
    label: "Vehicle Rental",
    emoji: "🚗",
    color: "from-yellow-600 to-orange-600",
    subcategories: ["Car Rental", "Exotic Cars", "SUV / Van", "Motorcycle", "Boat", "Jet Ski", "ATV", "RV"],
    serviceTemplates: [
      { title: "Luxury Sedan (Per Day)", price: 150, duration: 1440, price_type: "per_day" },
      { title: "SUV Rental (Per Day)", price: 120, duration: 1440, price_type: "per_day" },
      { title: "Exotic / Sports Car (Per Day)", price: 400, duration: 1440, price_type: "per_day" },
    ],
    tips: [
      "Upload multiple high-quality exterior and interior photos",
      "List exact car make, model, year, and features",
      "Set a security deposit and cancellation policy upfront",
    ],
    businessHint: "Enable instant booking to maximize utilization on your fleet.",
    availabilityNote: "Manage a blocked calendar carefully — gaps between rentals need cleaning time.",
    pricingNote: "Offer weekly and monthly discounts (10–20%) to fill low-demand periods.",
    marketplaceCategory: "property_rental",
  },
  {
    id: "real_estate",
    label: "Real Estate & Property",
    emoji: "🏡",
    color: "from-teal-600 to-green-600",
    subcategories: ["Short-Term Rental", "Long-Term Rental", "Real Estate Agent", "Property Manager", "Commercial"],
    serviceTemplates: [
      { title: "Studio / 1BR Short-Term Rental", price: 120, duration: 1440, price_type: "per_day" },
      { title: "Property Management (Monthly)", price: 200, duration: 0, price_type: "per_month" },
      { title: "Buyer/Seller Consultation", price: 0, duration: 60, price_type: "negotiable" },
    ],
    tips: [
      "Professional photos and a virtual tour dramatically increase bookings",
      "Highlight nearby attractions, beaches, and restaurants",
      "Add clear house rules and check-in/check-out instructions",
    ],
    businessHint: "Connect your property to the real estate marketplace for both rental and sale listings.",
    availabilityNote: "Season peaks are Nov–Apr (snowbirds). Adjust pricing dynamically.",
    pricingNote: "Dynamic pricing (higher on weekends/holidays) can increase revenue by 30%.",
    marketplaceCategory: "property_rental",
  },
];

export function getCategoryById(id) {
  return PROVIDER_CATEGORIES.find((c) => c.id === id) || null;
}